In [1]:
import numpy as np

In [2]:
# Python list 
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [5]:
# Numpy array
my_list  = np.array(my_list)

type(my_list)

numpy.ndarray

In [11]:
# Creating array using numpy

print(f"array 1: {np.arange(1,10)}")  # (start,stop,step)

print(f"array 2: {np.arange(1,10,2)}")

array 1: [1 2 3 4 5 6 7 8 9]
array 2: [1 3 5 7 9]


In [21]:
# Numpy Zeros/Ones array

np.zeros((3,2)) # (rows,columns)



array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.ones((3,2)) # (rows,columns)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
## Generating random numbers NumPy

# setting seed
np.random.seed(101)

# creating random numbers
array1 = np.random.random_integers(0,100,10) # (start,stop,size/number of digits)

<ipython-input-24-ad8f6cd6e61f>:7: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  array1 = np.random.random_integers(0,100,10)


In [25]:
array1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
array2 = np.random.random_integers(0,100,10)

<ipython-input-26-60d514ea4485>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  array2 = np.random.random_integers(0,100,10)


In [27]:
array2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [36]:
# Finding max value in array
print(array1.max())

# Finding min value in array
print(array1.min())

# Finding index of max value in array
print(array1.argmax())

# Finding shape of array
print(array1.shape)

# Reshape array
print(array1.reshape(2,5)) 

95
9
0
(10,)
[[95 11 81 70 63]
 [87 75  9 77 40]]


In [41]:
# creating np array and reshaping in same step to create matrix
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
# indexing matrix "mat"
row = 0
col = 1

mat[row,col]

1

In [58]:
# extracting column values
print("extracing column values :",mat[:,1],"\n") # ":" denotes all values for that space

# extracing row values
print("extracing row values :",mat[1,:],"\n")

# extracing column + row values within a range 

print("extracing row + column values within a range : \n",mat[0:3,0:3])


extracing column values : [ 1 11 21 31 41 51 61 71 81 91] 

extracing row values : [10 11 12 13 14 15 16 17 18 19] 

extracing row + column values within a range : 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [63]:
# extract and reshape
mat[1,:].reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
# select  and replace values
mat[0:3,0:3] = 0 
newmat = mat.copy()


In [66]:
newmat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])